# Generated by Django 2.2.7 on 2019-11-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='post_id',
            new_name='post',
        ),
    ]
