# Generated by Django 2.2.7 on 2019-11-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20191124_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='post',
            new_name='post_id',
        ),
    ]
