# Generated by Django 2.2.7 on 2019-11-24 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20191124_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='post_id',
            new_name='owner',
        ),
    ]
