# Generated by Django 2.2.7 on 2019-11-24 22:46

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20191124_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=django.core.files.storage.FileSystemStorage('/media/photos')),
        ),
    ]
