# Generated by Django 2.2.7 on 2019-11-25 00:01

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20191124_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=post.models.post_directory_path),
        ),
    ]
